### ISSUE TITLE
Message Preview Progress Indicator not Showing Progress

### ISSUE THREAD

**Issue by toreyhickman** [common-nighthawk/hello-its-me#34]
When previewing a message that I recorded, the progress indicator did not move to show how much of the message I'd heard.  I was hoping to see how long my message was by moving the progress indicator to the end, but that didn't work either.

Once the preview played completely, the progress indicator jumped to the end.  At that point, I was able to move it to any point along the timeline and resume playback from that point.

**Comment by common-nighthawk** [comment]
after lots of digging, this is cause by bug in chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=642012

seeking works straight-off in firefox.

it looks like the issue is being worked on.  i added a 'star' to help it get prioritized and become a watcher.

the only solution i can think of is to send the audio file to server and convert it into an mp3--but there are a few things i dont like about that approach.

**Comment by common-nighthawk** [comment]
jk!  i found a lovely workaround: http://stackoverflow.com/questions/38443084/how-can-i-add-predefined-length-to-audio-recorded-from-mediarecorder-in-chrome
